# GIT Leaks configuration for secret detection
# Detects hardcoded secrets, API keys, credentials

title = "KRL Analytics Suite - Secret Detection"

[extend]
# Use default gitleaks rules
useDefault = true

# Additional custom rules for KRL-specific secrets
[[rules]]
id = "krl-api-key"
description = "Detected KRL API key"
regex = '''krl_[a-zA-Z0-9]{32,}'''
tags = ["key", "KRL"]

[[rules]]
id = "fred-api-key"
description = "Detected FRED API key"
regex = '''[a-f0-9]{32}'''
path = '''(fred|data_connectors)'''
tags = ["key", "FRED"]

[[rules]]
id = "census-api-key"
description = "Detected Census API key"
regex = '''[a-f0-9]{40}'''
path = '''(census|data_connectors)'''
tags = ["key", "Census"]

[[rules]]
id = "aws-access-key"
description = "Detected AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["key", "AWS"]

[[rules]]
id = "generic-secret"
description = "Detected generic secret variable"
regex = '''(?i)(secret|password|token|api_key)\s*=\s*["'][^"']{8,}["']'''
tags = ["secret"]

[rules.allowlist]
# Allowlist common placeholder patterns within the generic-secret rule
regexes = [
    '''(?i)(secret|password|token|api_key)\s*=\s*["'](YOUR_|DEMO_|TEST_|EXAMPLE_)''',  # Placeholder prefixes
    '''(?i)(secret|password|token|api_key)\s*=\s*["'][A-Z_]+["']''',  # All caps placeholders
]

# Allowlist patterns to reduce false positives
[allowlist]
description = "Global allowlist"
paths = [
    '''\.md$''',  # Markdown files (documentation)
    '''\.rst$''',  # reStructuredText files (Sphinx docs)
    '''\.txt$''',  # Text files
    '''LICENSE''',  # License files
    '''CHANGELOG''',  # Changelog files
    '''^tests/fixtures/''',  # Test fixtures
    '''^docs/''',  # Documentation directory
]

regexes = [
    '''example\.com''',  # Example domains
    '''your[_-]api[_-]key''',  # Placeholder text variations
    '''YOUR_[A-Z_]+''',  # Placeholder environment variables
    '''DEMO_KEY''',  # Demo API key placeholder
    '''YOUR_KEY''',  # Generic placeholder
    '''your_[a-z_]+_key''',  # Lowercase placeholder variations
    '''secret_key_12345''',  # Example secret key
    '''xxx+''',  # Placeholder secrets
    '''123456789''',  # Example numeric values
    '''abcdefghijklmnop''',  # Example alphabetic values
    '''8ec3c8309e60d874eae960d407f15460''',  # Example FRED API key in docs
]
