# ----------------------------------------------------------------------
# © 2025 KR-Labs. All rights reserved.
# KR-Labs™ is a trademark of Quipu Research Labs, LLC,
# a subsidiary of Sudiata Giddasira, Inc.
# ----------------------------------------------------------------------
# SPDX-License-Identifier: Apache-2.0

name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Create stub krl-core package
      run: |
        mkdir -p /tmp/krl-core/src/krl_core
        cat > /tmp/krl-core/src/krl_core/__init__.py << 'EOF'
        """Stub krl-core for CI testing."""
        import logging
        
        class ConfigManager:
            def get(self, key, default=None):
                return default
        
        class FileCache:
            def __init__(self, *args, **kwargs):
                pass
            def get(self, key):
                return None
            def set(self, key, value, ttl=None):
                pass
        
        def get_logger(name):
            return logging.getLogger(name)
        EOF
        cat > /tmp/krl-core/setup.py << 'EOF'
        from setuptools import setup, find_packages
        setup(
            name="krl-core",
            version="0.1.0",
            package_dir={"": "src"},
            packages=find_packages(where="src"),
        )
        EOF
        pip install -e /tmp/krl-core
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,test]"
    
    - name: Run tests with coverage
      run: |
        pytest --cov=src --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
